# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6808db01e0c230909ce4f967a2051e9b5a6e69877b22d8abd64b8ddac4a3b4494d71bd6ffe4089dbe06bf4bb4004dcd58a411f4d9417ea49ff579f42f53eb3f

test:
  secret_key_base: 19857ea3b20acad51777e2ee5a813a19933cc78edab8854a10f5bef8dbd7f8d72f9831e5cc1ac9b4729fe98042eb268b04cc994471584ba2c7d65f135d6ff10c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
